### ISSUE TITLE
wkpdf doesn't work in Lion

### ISSUE THREAD

**Issue by siancu** [plessl/wkpdf#35] opened 2012-10-09 22:01 UTC
Hi,

Updated rubygems as per explained on the wkpdf homepage then installed wkpdf.

Now when I try to run it, I get the following:

```
/Library/Ruby/Site/1.8/rubygems/dependency.rb:247:in `to_specs': Could not find wkpdf (>= 0) amongst [] (Gem::LoadError)
    from /Library/Ruby/Site/1.8/rubygems/dependency.rb:256:in `to_spec'
    from /Library/Ruby/Site/1.8/rubygems.rb:1231:in `gem'
    from /usr/bin/wkpdf:22
```

Any ideas why and how can I fix this?

Thanks!

**Comment by plessl** [comment] 2012-10-12 19:40
Not really. A quick google search revealed that a similar problem is caused by rvm. Are you by chance using rvm?

**Comment by plessl** [comment] 2013-02-15 08:17
No update on this issue for several months, closing it.

**Closed as completed by plessl** 2013-02-15 08:17 UTC
