### ISSUE TITLE
Save delay causes an exception

### ISSUE THREAD

**Issue by mapanett** [plessl/wkpdf#14] opened 2010-02-19 00:18 UTC
When I add --save-delay I get the following exception:

2010-02-19 11:13:30.960 ruby[53317:60f] Controller#webView_didFinishLoadForFrame: OSX::OCMessageSendException: Can't get Objective-C method signature for selector 'scheduledTimerWithTimeInterval:target:selector:userInfo:repeat:' of receiver OSX::NSTimer
matt@mat/Library/Frameworks/RubyCocoa.framework/Resources/ruby/osx/objc/oc_wrapper.rb:50:in `ocm_send'matt@mat/Library/Frameworks/RubyCocoa.framework/Resources/ruby/osx/objc/oc_wrapper.rb:50:in`method_missing'
matt@mat/Library/Ruby/Gems/1.8/gems/wkpdf-0.3.8-universal-darwin/bin/../lib/controller.rb:33:in `webView_didFinishLoadForFrame'matt@mat/Library/Frameworks/RubyCocoa.framework/Resources/ruby/osx/objc/oc_wrapper.rb:50:in`ocm_send'
matt@mat/Library/Frameworks/RubyCocoa.framework/Resources/ruby/osx/objc/oc_wrapper.rb:50:in `method_missing'e pool (/Library/Ruby/Gems/1.8/gems/wkpdf-0.3.8-universal-darwin/bin/../lib/wkpdf.rb:103
2010-02-19 11:13:30.970 ruby[53317:60f] **\* WebKit discarded an uncaught exception in the webView:didFinishLoadForFrame: delegate: <RBException_OSX::OCMessageSendException> Can't get Objective-C method signature for selector 'scheduledTimerWithTimeInterval:target:selector:userInfo:repeat:' of receiver OSX::NSTimer

I'm using ruby 1.8.7 (2008-08-11 patchlevel 72) [universal-darwin10.0] on OS X 10.6.2

**Comment by plessl** [comment] 2010-02-21 13:05
Thanks for reporting this issue.

The problem was caused by an error I had accidentally inserted when porting wkpdf from Objective-C to RubyCocoa. The problem has been fixed in commit 864be40fd9032134007555fb9bf4f245770a6f18.

Also I have just released a new wkpdf version 0.3.9 that fixes this bug.

**Closed as completed by plessl** 2010-02-21 13:05 UTC
Labels: bug, accepted
